name: SeMiD-DeployTM

on:
  push:
    branches: [ master ]
    
jobs:
  SeMiD-DeployTM:
    runs-on: ubuntu-latest
    steps:
    - name: Deploying
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SEMIDHOST }}
        username: ${{ secrets.SSHUSERNAME }}
        password: ${{ secrets.SSHPASSWORD }}
        script: |
              cd /home/PreMiD/SeMiD
              git reset --hard
              git pull
              yarn
              yarn build
              pm2 reload /home/PreMiD/ecosystem.config.js --only SeMiD-website
